name: Build ZMK firmware

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/**"
      - "zephyr/**"
      - "boards/**"
      - "dts/**"
      - "include/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/**"
      - "zephyr/**"
      - "boards/**"
      - "dts/**"
      - "include/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: build.yaml
      config_path: config
      archive_name: firmware
